server:
  port: 8081

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456  # 添加eureka server认证，客户端需要账号才能注册到该eureka server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetchRegistry: false #  此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka #http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true #启用健康检查
